### ISSUE TITLE
Highlighting label/icon

### ISSUE THREAD

**Issue by andreicorpo** [FelixKratz/SketchyBar#36]
Somehow, higlighting labels/icons stopped working after some time. Colors do still work though.

Any idea why?

**Comment by FelixKratz** [comment]
Yeah, I know why I think #35. I hope this is fixed in the latest release on brew. Tell me if it is working after update 1.0.8

**Comment by andreicorpo** [comment]
It still doesn't seem to work. Seems like highlighting is not getting applied.

**Comment by FelixKratz** [comment]
Ok, this seems to be a different problem then. When I try it it is working. Can you maybe post a minimal config example where it is not working? Or your script you use?

**Comment by andreicorpo** [comment]
It seems I'm just stupid. I forgot to add the `associated_space` for my space components and this is why the highlighting wasn't working.

But what still doesn't seem to work, is changing the `label_font` on spaces which are selected.

This is my script:
```bash
#!/usr/bin/env bash

echo "Space $NAME"

if [ "$SELECTED" == "true" ]; then
	sketchybar -m freeze on
	sketchybar -m set "$NAME" label_highlight on
	sketchybar -m set "$NAME" icon_highlight on
	sketchybar -m set "$NAME" label_font "Hack Nerd Font:Bold:13.0"
	sketchybar -m freeze off
else
	sketchybar -m freeze on
	sketchybar -m set "$NAME" label_highlight off
	sketchybar -m set "$NAME" icon_highlight off
	sketchybar -m set "$NAME" label_font "Hack Nerd Font:Regular:12.0"
	sketchybar -m freeze off
fi
```

**Comment by FelixKratz** [comment]
Ah nice find, fixed in 4a90d43115ed774f3b860c1d8c3a94319a669425.
Will include this in the next release, if you want to try it you can install from HEAD with:
```bash
brew services stop sketchybar
brew uninstall sketchybar
brew install sketchybar --HEAD
brew services start sketchybar
```
