### ISSUE TITLE
Seg Fault - media_change

### ISSUE THREAD

**Issue by PhrantiK** [FelixKratz/SketchyBar#581]
I was getting super random crashes when changing from listening to music on spotify to watching a youtube vid. It wouldn't happen every time I switched and weirdly I could only replicate it with brave and not safari.

After a few hours fun with a robot teaching me how to use lldb I *think* I may have found the cause & potential fix:

https://github.com/FelixKratz/SketchyBar/blob/367c9d902d594ab43551ac99b923adf7ca129f39/src/media.m#L126

```
(lldb) env NSZombieEnabled=YES
(lldb) run

<snip>

(lldb) frame select 3
frame #3: 0x000000010002f8a4 sketchybar`__30-[media_context media_change:]_block_invoke_2(.block_descriptor=0x0000600003461440, dict=13 key/value pairs) at media.m:126:33
   123              NSString* title = [dict objectForKey:kMRMediaRemoteNowPlayingInfoTitle];
   124              NSString* album = [dict objectForKey:kMRMediaRemoteNowPlayingInfoAlbum];
   125              if (artist && title && album && name) {
-> 126                self.app = (char*)[app UTF8String];
   127                self.artist = (char*)[artist UTF8String];
   128                self.title = (char*)[title UTF8String];
   129                self.album = (char*)[album UTF8String];

(lldb) frame variable
(__NSDictionaryM *) dict = 0x0000600003ac9720 13 key/value pairs
(CFStringRef) name = 0x0000600003afd220 class name = _NSZombie_CFString
(media_context *) self = 0x0000600002fd3780
(_NSZombie_CFString *) app = 0x0000600003afd220 class name = _NSZombie_CFString
(__NSCFConstantString *) artist = 0x000000020ac0d1a8 @""
(__NSCFString *) title = 0x0000600003468ab0 @"Advanced example | Video.js"
(__NSCFConstantString *) album = 0x000000020ac0d1a8 @""
(NSString *) mime_type = 0x0000000107000806
(NSData *) ns_data = 0x0000000205dc2000
(CGImageRef) image = 0x00000001b9175b21

(lldb) p (char *)[app UTF8String]
2024-07-21 02:04:03.015142+0800 sketchybar[27064:76326460] *** -[CFString respondsToSelector:]: message sent to deallocated instance 0x600003afd220
error: warning: couldn't get cmd pointer (substituting NULL): no variable named '_cmd' found in this frame
error: Execution was interrupted, reason: EXC_BREAKPOINT (code=1, subcode=0x19e1d7608).
The process has been returned to the state before expression evaluation.
```

This line stops app from becoming a zombie:

```diff
diff --git a/src/media.m b/src/media.m
index c9d6ac9..aef481f 100644
--- a/src/media.m
+++ b/src/media.m
@@ -115,9 +115,12 @@ - (void)media_change:(NSNotification *)notification {
   if (!g_media_events) return;
   MRMediaRemoteGetNowPlayingApplicationDisplayName(0, dispatch_get_main_queue(), ^(CFStringRef name) {
     @autoreleasepool {
+
+      NSString* app = [(NSString*)CFBridgingRelease(name) copy];
+
       MRMediaRemoteGetNowPlayingInfo(dispatch_get_main_queue(), ^(NSDictionary* dict) {
         @autoreleasepool {
-          if (dict && name) {
+          if (dict && app) {
             NSString* app = (NSString*)name;
             NSString* artist = [dict objectForKey:kMRMediaRemoteNowPlayingInfoArtist];
             NSString* title = [dict objectForKey:kMRMediaRemoteNowPlayingInfoTitle];
```

I may be completely off base here but it seems to have stopped the crash. Either way please close this out, I don't want to pollute your issues with BS just in case it is. :)

Also not sure if the above crash is related to SbarLua somehow, I moved my config to lua and didn't have a media plugin in my old shell config. Cheers for making that BTW, it's super rad!

**Comment by SpyMachine** [comment]
Oh man, I've been debugging the same issue for the past hour! Mine might be a bit different though, I'm having trouble using the Youtube Music Desktop App. I have a crash report, @PhrantiK is this similar to what you were seeing?

[sketchybar-2024-07-20-145506.log](https://github.com/user-attachments/files/16322062/sketchybar-2024-07-20-145506.log)

**Comment by PhrantiK** [comment]
Yep, looks to be the same. Here's parts of one from mine:

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000d27d0d619190 -> 0x0000527d0d619190 (possible pointer authentication failure)
Exception Codes:       0x0000000000000001, 0x0000d27d0d619190

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [93067]

VM Region Info: 0x527d0d619190 is not in any region.  Bytes after previous region: 90216012550545  Bytes before following region: 14856067378800
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  reserved VM address space (unallocated)
--->  GAP OF 0x5f9000000000 BYTES
      MALLOC_NANO              600000000000-600020000000 [512.0M] rw-/rwx SM=PRV  

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	       0x19dbb5c20 objc_msgSend + 32
1   sketchybar                    	       0x1049e0594 __30-[media_context media_change:]_block_invoke_2 + 156
2   MediaRemote                   	       0x1b8e161fc __MRMediaRemoteGetNowPlayingInfoForOrigin_block_invoke + 100
3   MediaRemote                   	       0x1b8e15fb0 __MRMediaRemoteGetNowPlayingInfoForPlayer_block_invoke + 92
4   MediaRemote                   	       0x1b8e18828 ___MRGetNowPlayingInfo_block_invoke_2 + 68
5   libdispatch.dylib             	       0x19ddd8750 _dispatch_call_block_and_release + 32
6   libdispatch.dylib             	       0x19ddda3e8 _dispatch_client_callout + 20
7   libdispatch.dylib             	       0x19dde8bb8 _dispatch_main_queue_drain + 988
8   libdispatch.dylib             	       0x19dde87cc _dispatch_main_queue_callback_4CF + 44
9   CoreFoundation                	       0x19e0abad4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
10  CoreFoundation                	       0x19e069258 __CFRunLoopRun + 1996
11  CoreFoundation                	       0x19e068434 CFRunLoopRunSpecific + 608
12  HIToolbox                     	       0x1a880c19c RunCurrentEventLoopInMode + 292
13  HIToolbox                     	       0x1a880bfd8 ReceiveNextEventCommon + 648
14  HIToolbox                     	       0x1a8955240 RunApplicationEventLoop + 168
15  sketchybar                    	       0x1049bca3c main + 876
16  dyld                          	       0x19dc020e0 start + 2360
```

**Comment by FelixKratz** [comment]
Could you try the patch I have provided on master?

**Comment by PhrantiK** [comment]
Fixed, cheers!

**Comment by SpyMachine** [comment]
I can confirm I'm not getting seg faults either, thank you!

I'm still having an issue where I'm not receiving the event when media changes on the [Youtube Music Desktop Player](https://github.com/th-ch/youtube-music) but it works everywhere else so I assume this is more an issue on that side. Will try there first.
